# Generated by Django 4.2.7 on 2023-11-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_crimedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimedata',
            name='anio_hecho',
            field=models.CharField(default='0000', max_length=255),
        ),
        migrations.AddField(
            model_name='crimedata',
            name='colonia_hecho',
            field=models.CharField(default='0000', max_length=100),
        ),
        migrations.AddField(
            model_name='crimedata',
            name='hora_hecho',
            field=models.CharField(default='0000', max_length=255),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='alcaldia_hecho',
            field=models.CharField(default='0000', max_length=100),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='categoria',
            field=models.CharField(default='0000', max_length=255),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='delito',
            field=models.CharField(default='0000', max_length=255),
        ),
    ]
