# Generated by Django 4.2.7 on 2023-11-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_crimedata_anio_hecho_crimedata_colonia_hecho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimedata',
            name='latitud',
            field=models.FloatField(default='0000', max_length=200),
        ),
        migrations.AddField(
            model_name='crimedata',
            name='longitud',
            field=models.FloatField(default='0000', max_length=200),
        ),
    ]
