# Generated by Django 4.2.7 on 2023-11-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_crimedata_latitud_crimedata_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimedata',
            name='latitud',
            field=models.CharField(default='0000', max_length=200),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='longitud',
            field=models.CharField(default='0000', max_length=200),
        ),
    ]
