# Generated by Django 4.2.7 on 2023-12-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_crimedata_latitud_alter_crimedata_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimedata',
            name='direccion',
            field=models.CharField(default='0000', max_length=500),
        ),
    ]
