# Generated by Django 4.2.7 on 2023-12-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_crimedata_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimedata',
            name='fecha_hecho',
            field=models.CharField(default='DD/MM/YYYY', max_length=255),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='anio_hecho',
            field=models.CharField(default='0000', max_length=255),
        ),
    ]
