# Generated by Django 4.2.7 on 2023-12-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_crimedata_fecha_hecho_alter_crimedata_anio_hecho'),
    ]

    operations = [
      
        migrations.AlterField(
            model_name='crimedata',
            name='alcaldia_hecho',
            field=models.CharField(default='ALCALDIA-No-especificada', max_length=100),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='anio_hecho',
            field=models.CharField(default='AÑO-No-especificado', max_length=100),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='categoria',
            field=models.CharField(default='CATEGORIA-No-especificada', max_length=100),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='colonia_hecho',
            field=models.CharField(default='COLONIA-No-especificada', max_length=100),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='delito',
            field=models.CharField(default='DELITO-No-especificado', max_length=255),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='hora_hecho',
            field=models.CharField(default='HORA-No-especificada', max_length=100),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='latitud',
            field=models.CharField(default='LATITUD-No-especificada', max_length=255),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='longitud',
            field=models.CharField(default='LONGITUD-No-especificada', max_length=255),
        ),
    ]
