# Generated by Django 4.2.7 on 2023-12-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_crimedata_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimedata',
            name='direccion',
            field=models.CharField(default='DIRECCION-No-especificada', max_length=500),
        ),
        migrations.AddField(
            model_name='crimedata',
            name='fecha_hecho',
            field=models.CharField(default='FECHA-No-especificada', max_length=100),
        ),
    ]
