# Generated by Django 4.2.7 on 2024-01-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_crimedata_user_report_alter_crimedata_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimedata',
            name='user_report',
            field=models.CharField(default='Fiscalía General de Justicia (FGJ) de la Ciudad de México', max_length=100),
        ),
         migrations.AddField(
            model_name='crimedata',
            name='direccion',
            field=models.CharField(default='DIRECCION-No-especificada', max_length=500),
        ),
        migrations.AddField(
            model_name='crimedata',
            name='fecha_hecho',
            field=models.CharField(default='FECHA-No-especificada', max_length=100),
        ),
    ]
