# Generated by Django 4.2.7 on 2024-01-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_crimedata_user_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimedata',
            name='alcaldia_hecho',
            field=models.CharField(default='ALCALDIA-No-especificada', max_length=50),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='categoria',
            field=models.CharField(default='CATEGORIA-No-especificada', max_length=50),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='colonia_hecho',
            field=models.CharField(default='COLONIA-No-especificada', max_length=50),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='fecha_hecho',
            field=models.CharField(default='FECHA-No-especificada', max_length=50),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='hora_hecho',
            field=models.CharField(default='HORA-No-especificada', max_length=50),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='user_report',
            field=models.CharField(default='Fiscalía General de Justicia (FGJ) de la Ciudad de México', max_length=50),
        ),
    ]
